---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: flm
spec:
   replicas: 5
   selector:
      matchLabels:
        app: swiggy
   template:
      metadata:
        labels:
          app: swiggy
      spec:
        containers:
          - name: cont01
            image: shaikmustafa/paytm:movie
            ports:
            - containerPort: 80
